# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 331ce0935bf06f24e46d1dcb1be6e9fc8b0c85ead3a08cf74ea5659c3d81ea1001194ba794045e33a3b451955e310be12f173c57b5f5e595f3213e721f7d67d6

test:
  secret_key_base: fe3620bcbaf2ab98378bd25bfbd51509356cb10105f2d8504bee04d3d0b84b2bda9f1c3935cda209ce3cdf8470ccec37f7c4d9fc2de649a975527a9aa6382dc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
